print("Welcome to the Band Name Generator")
city = input("What's name of the city you grew up in?\n")
print("\n")
pet = input("What's your pet name?\n")
print("\n")
print("Your band name could be ", city, " ", pet)
